/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router';

// Import Routes

import { Route as rootRoute } from './routes/__root';
import { Route as RegisterImport } from './routes/register';
import { Route as SetupMfaImport } from './routes/Setup-mfa';
import { Route as LoginImport } from './routes/Login';
import { Route as InputTotpImport } from './routes/Input-totp';
import { Route as IndexImport } from './routes/index';
import { Route as DashboardLayoutImport } from './routes/dashboard/_layout';
import { Route as DashboardLayoutIndexImport } from './routes/dashboard/_layout/index';

// Create Virtual Routes

const DashboardImport = createFileRoute('/dashboard')();

// Create/Update Routes

const DashboardRoute = DashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any);

const RegisterRoute = RegisterImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRoute,
} as any);

const SetupMfaRoute = SetupMfaImport.update({
  id: '/Setup-mfa',
  path: '/Setup-mfa',
  getParentRoute: () => rootRoute,
} as any);

const LoginRoute = LoginImport.update({
  id: '/Login',
  path: '/Login',
  getParentRoute: () => rootRoute,
} as any);

const InputTotpRoute = InputTotpImport.update({
  id: '/Input-totp',
  path: '/Input-totp',
  getParentRoute: () => rootRoute,
} as any);

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any);

const DashboardLayoutRoute = DashboardLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => DashboardRoute,
} as any);

const DashboardLayoutIndexRoute = DashboardLayoutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardLayoutRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    '/Input-totp': {
      id: '/Input-totp';
      path: '/Input-totp';
      fullPath: '/Input-totp';
      preLoaderRoute: typeof InputTotpImport;
      parentRoute: typeof rootRoute;
    };
    '/Login': {
      id: '/Login';
      path: '/Login';
      fullPath: '/Login';
      preLoaderRoute: typeof LoginImport;
      parentRoute: typeof rootRoute;
    };
    '/Setup-mfa': {
      id: '/Setup-mfa';
      path: '/Setup-mfa';
      fullPath: '/Setup-mfa';
      preLoaderRoute: typeof SetupMfaImport;
      parentRoute: typeof rootRoute;
    };
    '/register': {
      id: '/register';
      path: '/register';
      fullPath: '/register';
      preLoaderRoute: typeof RegisterImport;
      parentRoute: typeof rootRoute;
    };
    '/dashboard': {
      id: '/dashboard';
      path: '/dashboard';
      fullPath: '/dashboard';
      preLoaderRoute: typeof DashboardImport;
      parentRoute: typeof rootRoute;
    };
    '/dashboard/_layout': {
      id: '/dashboard/_layout';
      path: '/dashboard';
      fullPath: '/dashboard';
      preLoaderRoute: typeof DashboardLayoutImport;
      parentRoute: typeof DashboardRoute;
    };
    '/dashboard/_layout/': {
      id: '/dashboard/_layout/';
      path: '/';
      fullPath: '/dashboard/';
      preLoaderRoute: typeof DashboardLayoutIndexImport;
      parentRoute: typeof DashboardLayoutImport;
    };
  }
}

// Create and export the route tree

interface DashboardLayoutRouteChildren {
  DashboardLayoutIndexRoute: typeof DashboardLayoutIndexRoute;
}

const DashboardLayoutRouteChildren: DashboardLayoutRouteChildren = {
  DashboardLayoutIndexRoute: DashboardLayoutIndexRoute,
};

const DashboardLayoutRouteWithChildren = DashboardLayoutRoute._addFileChildren(
  DashboardLayoutRouteChildren
);

interface DashboardRouteChildren {
  DashboardLayoutRoute: typeof DashboardLayoutRouteWithChildren;
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardLayoutRoute: DashboardLayoutRouteWithChildren,
};

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren
);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/Input-totp': typeof InputTotpRoute;
  '/Login': typeof LoginRoute;
  '/Setup-mfa': typeof SetupMfaRoute;
  '/register': typeof RegisterRoute;
  '/dashboard': typeof DashboardLayoutRouteWithChildren;
  '/dashboard/': typeof DashboardLayoutIndexRoute;
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/Input-totp': typeof InputTotpRoute;
  '/Login': typeof LoginRoute;
  '/Setup-mfa': typeof SetupMfaRoute;
  '/register': typeof RegisterRoute;
  '/dashboard': typeof DashboardLayoutIndexRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  '/': typeof IndexRoute;
  '/Input-totp': typeof InputTotpRoute;
  '/Login': typeof LoginRoute;
  '/Setup-mfa': typeof SetupMfaRoute;
  '/register': typeof RegisterRoute;
  '/dashboard': typeof DashboardRouteWithChildren;
  '/dashboard/_layout': typeof DashboardLayoutRouteWithChildren;
  '/dashboard/_layout/': typeof DashboardLayoutIndexRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/Input-totp'
    | '/Login'
    | '/Setup-mfa'
    | '/register'
    | '/dashboard'
    | '/dashboard/';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/Input-totp'
    | '/Login'
    | '/Setup-mfa'
    | '/register'
    | '/dashboard';
  id:
    | '__root__'
    | '/'
    | '/Input-totp'
    | '/Login'
    | '/Setup-mfa'
    | '/register'
    | '/dashboard'
    | '/dashboard/_layout'
    | '/dashboard/_layout/';
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  InputTotpRoute: typeof InputTotpRoute;
  LoginRoute: typeof LoginRoute;
  SetupMfaRoute: typeof SetupMfaRoute;
  RegisterRoute: typeof RegisterRoute;
  DashboardRoute: typeof DashboardRouteWithChildren;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InputTotpRoute: InputTotpRoute,
  LoginRoute: LoginRoute,
  SetupMfaRoute: SetupMfaRoute,
  RegisterRoute: RegisterRoute,
  DashboardRoute: DashboardRouteWithChildren,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/Input-totp",
        "/Login",
        "/Setup-mfa",
        "/register",
        "/dashboard"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/Input-totp": {
      "filePath": "Input-totp.tsx"
    },
    "/Login": {
      "filePath": "Login.tsx"
    },
    "/Setup-mfa": {
      "filePath": "Setup-mfa.tsx"
    },
    "/register": {
      "filePath": "register.tsx"
    },
    "/dashboard": {
      "filePath": "dashboard",
      "children": [
        "/dashboard/_layout"
      ]
    },
    "/dashboard/_layout": {
      "filePath": "dashboard/_layout.tsx",
      "parent": "/dashboard",
      "children": [
        "/dashboard/_layout/"
      ]
    },
    "/dashboard/_layout/": {
      "filePath": "dashboard/_layout/index.tsx",
      "parent": "/dashboard/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
